package presenters;

public enum Action {
	ADD_HOUSE, ADD_APARTMENT, ADD_BUILDING, 
	
	REMOVE,CANCEL, 
	
	GYM, PARK, BBQ, HALL, SWIMMING,
	
	SHOW_DIALOG_ADD_USER, ADD_USER, SHOW_DIALOG_PURCHASE_OWNERSHIP, PURCHASE_OWNERSHIP,
	VALIDATE_LOGIN_USER, SHOW_DIALOG_REPORT_DEBT, GENERATE_TABLE_REPORT, EXIT, FILTER_DEBT
}
