package constants;

import java.awt.Color;
import java.awt.Font;

public class Constant {

	public static final String REQUEST_VALIDATE_USER_CLIENT = "REQUEST_VALIDATE_USER_CLIENT";
	public static final String ADD_HOUSE_TXT = "Add House";
	public static final String ADD_BUILDING_TXT = "Add Building";
	public static final String ADD_APARTMENT_TXT = "Add Aparment";
	public static final String ADD_CO_OWNERSHIP_TXT = "Co-Ownership";
	public static final String ADD_USER_TXT = "Add User";
	public static final String ADD_GYM_TXT = "Gym";
	public static final String ADD_PARK_TXT = "Park";
	public static final String ADD_BBQ_ZONE_TXT = "BBQ Zone";
	public static final String ADD_COMMUNITY_HALL_TXT = "Community Hall";
	public static final String ADD_SWIMMING_POOL_TXT = "Swimming Pool";
	public static final String REGISTER_OWNERSHIP_TXT = "Register Ownership";
	public static final String ENTER_CO_OWNERSHIP = "Select the co-ownership to add:";
	public static final String TITLE_APP = "Luxury Apartments - Client";
	public static final String ADD_TXT = "Add ";
	public static final String SEARCH = "Search";
	public static final String CANCEL_TXT = "Cancel";
	public static final String REMOVE_TXT = "Remove";
	public static final String INPUT_ID_TXT = "Enter your ID";
	public static final String ID_TXT = "ID";
	public static final String SEARCH_TITLE = "Search matches";
	public static final String ADD_INVOICE_TXT = "Add Invoice";
	public static final String WATER_TXT = "Water";
	public static final String LIGHT_TXT = "Light";
	public static final String GAS_TXT = "Gas";
	public static final String INTERNET_TXT = "Internet";
	public static final String ENTER_DATE_INVOICE_MESSAGE = "Enter date of the invoice:";
	public static final String ENTER_VALUE_INVOICE_MESSAGE = "Enter value of the invoice ($)";
	public static final String OWNERSHIP_TXT = "Ownership";
	public static final String PRIVILEGES_TXT = "Privileges";
	public static final String ENTER_YOUR_USER_NAME_MESSAGE = "Enter your username: ";
	public static final String TYPE_OWNERSHIP_TXT = "TYPE OWNERSHIP";
	public static final String PURCHASE_TXT = "PURCHASE";
	public static final String ASSIGN_OWNERSHIP_TO_CLIENT_TXT = "Assign ownership";
	public static final String ADD_OWNERSHIP_TXT = "Add Ownership";
	public static final String LOGIN_TXT = "LogIn";
	public static final String REQUEST_USER_ADMIN = "Administrator";
	public static final String REQUEST_USER_CLIENT = "Client";
	public static final String HOUSE_TXT = "House";
	public static final String APARTMENT_TXT = "Apartment";
	public static final String REQUEST_VALIDATE_USER_ADMIN = "VALIDATE_USER_ADMIN";
	public static final String GENERATE_REPORT_TXT = "Generate Report";
	public static final String REQUEST_GENERATE_INVOICE = "Generate invoice";
	public static final String REPORTS_TXT = "Reports";
	public static final String PATH_ICON_APP = "/imgs/iconApp.png";
	public static final String ICON_PATH_GYM = "/imgs/dumbell.png";
	public static final String ICON_PATH_PARK = "/imgs/slide.png";
	public static final String ICON_PATH_BBQ = "/imgs/bbq.png";
	public static final String ICON_PATH_HALL = "/imgs/hall.png";
	public static final String ICON_PATH_SWIMMING = "/imgs/swimming.png";
	public static final String ICON_PATH_ADD_HOUSE = "/imgs/addHouse.png";
	public static final String ICON_PATH_ADD_BUILDING = "/imgs/addBuilding.png";
	public static final String ICON_PATH_USER = "/imgs/user.png";
	public static final String ICON_PATH_REMOVE = "/imgs/remove.png";
	public static final String PATH_ICON_ADD_USER = "/imgs/addUserIcon.png";
	public static final String ICON_PATH_BTN_PURCHASE = "/imgs/purchase.png";
	public static final String ICON_PATH_TO_PURCHASE = "/imgs/toPurchase.png";
	public static final int SIZE_WINDOW = 600;
	public static final int SIZE_DIALOG_WIDTH = 400;
	public static final int SIZE_DIALOG_HEIGHT = 300;
	public static final int SIZE_DIALOG_REMOVE_WIDTH = 400;
	public static final int SIZE_DIALOG_REMOVE_HEIGHT = 250;
	public static final Color MY_COLOR_RED = Color.decode("#f50537");
	public static final Color MY_COLOR_BLACK = Color.decode("#000000");
	public static final Color MY_COLOR_WHITE = Color.decode("#ffffff");
	public static final Color MY_COLOR_GREEN_LIGHT = Color.decode("#c9c9c9");
	public static final Color MY_COLOR_GREEN = Color.decode("#4dc47d");
	public static final Color MY_ORANGE_COLOR = Color.decode("#f47721");
	public static final Font FONT_CAMBRIA_DATA = new Font("Cambria", Font.PLAIN, 16);
	public static final Font FONT_CANDARA_DATA = new Font("Candara", Font.BOLD, 22);
}